/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      colors: {
        black: '#000000',
        'brutal-blue': '#0000FF',
        'safety-orange': '#FF5C00',
        'warning-red': '#FF0000',
        'success-green': '#00C853',
        surface: '#FFFFFF',
        'surface-bright': '#F9F9F9',
        'surface-dim': '#DADADA',
        'surface-variant': '#E2E2E2',
        'surface-container': '#EEEEEE',
        'surface-container-high': '#E8E8E8',
        'surface-container-highest': '#E2E2E2',
        'surface-container-low': '#F3F3F4',
        'surface-container-lowest': '#FFFFFF',
        background: '#FFFFFF',
        'border-strong': '#000000',
        'border-subtle': '#000000',
        'border-black': '#000000',
        'on-surface': '#000000',
        'on-surface-variant': '#454558',
        'status-live': '#FF0000',
        'status-warning': '#FF5C00',
        'status-success': '#00C853',
        primary: '#0000FF',
        'primary-container': '#0000FF',
        secondary: '#A33800',
        'secondary-container': '#CD4800',
        outline: '#757589',
        'outline-variant': '#C5C4DB',
        brand: {
          50: '#f0f7ff',
          100: '#e0effe',
          200: '#badffd',
          300: '#7cc5fc',
          400: '#36a8f8',
          500: '#0000ff',
          600: '#0000dd',
          700: '#0000bb',
          800: '#000099',
          900: '#00006e',
          950: '#000000',
        },
      },
      boxShadow: {
        brutal: '4px 4px 0px 0px #000000',
        'brutal-sm': '2px 2px 0px 0px #000000',
        'brutal-lg': '6px 6px 0px 0px #000000',
        'brutal-blue': '4px 4px 0px 0px #0000FF',
        'brutal-orange': '4px 4px 0px 0px #FF5C00',
        'brutal-red': '4px 4px 0px 0px #FF0000',
        'brutal-green': '4px 4px 0px 0px #00C853',
        tactical: '4px 4px 0px 0px #000000',
        'tactical-sm': '2px 2px 0px 0px #000000',
        'tactical-gold': '4px 4px 0px 0px #FF5C00',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out forwards',
        'slide-up': 'slideUp 0.25s ease-out forwards',
        'scale-in': 'scaleIn 0.2s ease-out forwards',
        'slide-from-right': 'slideFromRight 0.25s cubic-bezier(0.25,0.46,0.45,0.94) forwards',
        'slide-from-left': 'slideFromLeft 0.25s cubic-bezier(0.25,0.46,0.45,0.94) forwards',
        'pulse-live': 'pulseLive 1.2s infinite ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(12px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.96)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        slideFromRight: {
          '0%': { transform: 'translateX(24px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideFromLeft: {
          '0%': { transform: 'translateX(-24px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        pulseLive: {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.6', transform: 'scale(1.04)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
